# The URL the site will be built for
base_url = "https://bjornstad.dev"
# title and description
title = 'bjornstad.dev'
description = 'The Spacebar, Linux, and the Occasional Rant'

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "minigawa"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = false # A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
ignored_content = []

# When set to "true", a feed is automatically generated.
generate_feed = true

# The filename to use for the feed. Used as the template filename, too.
# Defaults to "atom.xml", which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filename = "atom.xml"

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
# feed_limit = 20

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
hard_link_static = false

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
	{name = "tags", feed = true},
]

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_theme = "boron"
highlight_code = true

[extra]
# Put all your custom variables here
author = 'Bailey Bjornstad'
contact = 'bailey@bjornstad.dev'
logo_text = "bjornstad.dev "

use_hack_full_font = true

menu_items = [
	{name = "about", url = "$BASE_URL"},
	{name = "the spacebar", url = "$BASE_URL/spacebar"},
	{name = "pgp", url = "$BASE_URL/pgp"},
	{name = "contributions", url = "$BASE_URL/contributions"},
	{name = "links", url = "$BASE_URL/links"},
	{name = "github", url = "https://github.com/bbjornstad", newtab = true}
]
page_titles = "combined"

[extra.profileimg]
profile_picture = "$BASE_URL/static/bjornstad_profile.jpg"

[extra.spacebar]
	[extra.spacebar.logoline]
	logo = "󱁐 The Spacebar 󱁐"
	separator = "."
	accent = ""


